### ISSUE TITLE
Add RTL support

### ISSUE THREAD

**Issue by AyoobMH** [usernotnull/tall-toasts#168]
### Description

- Add RTL support to the toast notification. Currently, the `contnet.blade.php` would only display messages in LTR.
- This feature would allow other languages, such as Arabic and Persian, to display messages in a better format, if displayed in RTL.

### Screenshots
This screenshot shows what the message would look like if RTL is enabled.

https://user-images.githubusercontent.com/37803924/169199319-661ff6af-f232-47b5-b383-a90481c54b9d.mov

**Comment by usernotnull** [comment]
Hi @AyoobMH,

Release v1.5.0 published with RTL support!

If you have further comments, you can reopen this issue.

**Comment by MechJosh0** [comment]
@usernotnull It is worth adding this to the readme that `dir="ltr"` should be added to the `html` element otherwise your RTL classes will not work. I've just spent a couple of hours trying to work out why tall-toasts was suddenly rendering incorrectly.

**Comment by usernotnull** [comment]
@MechJosh0 If your layout is direction-dependent and uses TailwindCSS, then this info should be found the tailwindcss docs as it is not only related to this library.

However, I'll do actually add a memo about the default layout having RTL support and add that info and relative links to it,

**Comment by MechJosh0** [comment]
My layout wasn't direction-dependent until your package made it direction-dependent, and your package wasn't telling me it was now direction-dependent. That's the issue I wanted to raise :)

Thanks for updating the readme for others to be aware of, and thanks for the package.
