### ISSUE TITLE
Livewire blade component weird comportement

### ISSUE THREAD

**Issue by Ashk2a** [usernotnull/tall-toasts#18]
### Description

Hello, I don't understand this bug, sometime (1/2) the toast livewire component have a strange comportment... The component render the same toast until infinite.. I precise that the session->get('toasts') only contains one item.

I'm sorry for my bad english..

### To Reproduce

You can see my implementation in my public project : 

[master.blade.php](https://github.com/Ashk2a/wowlf/blob/b6eb94156d6fd5ed6db627391ee7c405e7c8a1b3/resources/views/layouts/master.blade.php) : master layout where is put assets

[default.blade.php](https://github.com/Ashk2a/wowlf/blob/b6eb94156d6fd5ed6db627391ee7c405e7c8a1b3/resources/views/layouts/default.blade.php) : default layout where i put the livewire component

[vendor.js](https://github.com/Ashk2a/wowlf/blob/b6eb94156d6fd5ed6db627391ee7c405e7c8a1b3/resources/js/vendor.js) : Alpine package implementation

[webpack.mix.js](https://github.com/Ashk2a/wowlf/blob/b6eb94156d6fd5ed6db627391ee7c405e7c8a1b3/webpack.mix.js) : webpack mix configuration

[LoginController:php](https://github.com/Ashk2a/wowlf/blob/b6eb94156d6fd5ed6db627391ee7c405e7c8a1b3/app/Http/Controllers/Auth/LoginController.php#L50) : a simple controller

[HasFlashToast](https://github.com/Ashk2a/wowlf/blob/b6eb94156d6fd5ed6db627391ee7c405e7c8a1b3/app/Abstractions/Http/HasFlashToast.php#L22) : a little trait (change nothing) to customize my usage of your package 

### Expected behavior

Just render one toast could be cool :sob: 

### Screenshots

My render (with the number of AJAX call increment)

![image](https://user-images.githubusercontent.com/1284914/139508401-c1efa83f-2de9-413d-a113-bbf8e9047461.png)

### Additional context

My composer.json packages

```json
"require": {
    "php": "^8.0",
    "ext-gmp": "*",
    "ext-pdo": "*",
    "fruitcake/laravel-cors": "^2.0",
    "guzzlehttp/guzzle": "^7.0.1",
    "laravel/framework": "^8.54",
    "laravel/octane": "^1.0",
    "laravel/tinker": "^2.5",
    "livewire/livewire": "^2.6",
    "spatie/laravel-activitylog": "^4.3",
    "spatie/laravel-permission": "^5.1",
    "usernotnull/tall-toasts": "^1.0"
},
"require-dev": {
    "barryvdh/laravel-debugbar": "^3.6",
    "barryvdh/laravel-ide-helper": "^2.10",
    "facade/ignition": "^2.5",
    "fakerphp/faker": "^1.9.1",
    "mockery/mockery": "^1.4.4",
    "nunomaduro/collision": "^5.10",
    "phpunit/phpunit": "^9.5.8",
    "roave/security-advisories": "dev-latest"
}
```

**Comment by usernotnull** [comment]
Hye @Ashk2a ,

Thanks for reporting. It may be a bug introduced in v1.1.0.

Can you revert to v1.0.0 and let me know if there's still an issue?

In the meantime, I'll see where the issue could be, as it's hard when it's not consistently happening...

**Comment by usernotnull** [comment]
Okay, I found the issue. It's a race condition between frontend and backend.

To consistently reproduce, immediately before the page fully loads, navigate to another tab, wait a couple of seconds, then come back to the page. It'll infinitely try to request the backend to update the toasts array.

Will write a fix within 24 hours...
