### ISSUE TITLE
Error using Vite, doesnt build. 

### ISSUE THREAD

**Issue by sawirricardo** [usernotnull/tall-toasts#201]
### Description

Error: 'default' is not exported by vendor/usernotnull/tall-toasts/dist/js/tall-toasts.js, imported by resources/js/app.js

### To Reproduce

setup Vite, preferrably using mix first, then migrate to vite.
npm run build

### Expected behavior

It builds

### Screenshots

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/37329575/176397479-7728e2cf-eb20-4186-8c09-77ca2fb6a702.png">

### Additional context
None

**Comment by csoutham** [comment]
@sawirricardo I had this issue too and looking at the source, the fix is to use the code from resources/js.
`import ToastComponent from '../../vendor/usernotnull/tall-toasts/resources/js/tall-toasts';`
This will compile correctly using Vite.

**Comment by sawirricardo** [comment]
> @sawirricardo I had this issue too and looking at the source, the fix is to use the code from resources/js. `import ToastComponent from '../../vendor/usernotnull/tall-toasts/resources/js/tall-toasts';` This will compile correctly using Vite.

Thanks, it works!

**Comment by RikoDEV** [comment]
The @csoutham solution works only partially for me. Build passes, however when launching the application it shows a livewire related error which is not present in laravel-mix.

![image](https://user-images.githubusercontent.com/18230443/176900020-f252f885-7b19-40c5-97eb-4cc037c877e9.png)
![image](https://user-images.githubusercontent.com/18230443/176900472-9dcb4dfc-e300-41da-ace6-a4cf1e2fbecc.png)
![image](https://user-images.githubusercontent.com/18230443/176900822-e152649d-2ff6-4458-878b-6b191c339456.png)

app.js
```js
import './bootstrap'
import Alpine from 'alpinejs'
import ToastComponent from '../../vendor/usernotnull/tall-toasts/resources/js/tall-toasts';

Alpine.data('ToastComponent', ToastComponent)

window.Alpine = Alpine;
Alpine.start();
```

**Comment by timgavin** [comment]
I recommend putting something in the readme regarding this issue. I have a new build with Vite and encountered this issue. Took some digging to find that @csoutham 's solution fixed it. Thanks!

**Comment by usernotnull** [comment]
I'm open for PRs to update README, since I can't test using Vite. My line of work temporarily changed and not coding ATM.

**Comment by jeffwhansen** [comment]
PR to update README has been merged into main.
