### ISSUE TITLE
Toasts appear and disappear quick

### ISSUE THREAD

**Issue by SrPeterr** [usernotnull/tall-toasts#275]
### Discussed in https://github.com/usernotnull/tall-toasts/discussions/270

<div type='discussions-op-text'>

<sup>Originally posted by **SrPeterr** October  7, 2022</sup>
Hi!
Well I'm having this problem with toasts, they appear and disappear quick and with no style
This is my controller:
```
class BugsController extends Controller
{
    public function index() {

        if(Auth::check()) {
            $issues = GitHub::issues()->all('confidential', 'confidential');
            toast()->info('Notification from the backend...', 'The Title')->push();
            return view("bugs", ["issues" => $issues]);
        } else {
            return redirect('/');
        }
    	
    }
}
```
This is how its on my blade:
```
@livewireStyles
@toastScripts
<script src="{{ mix('js/app.js') }}" defer></script>
</head>
<body>
    @livewireScripts
    <livewire:toasts />
```

And I have run `npm run dev` and `php artisan view:clear`

![2022-10-07-22-22-06](https://user-images.githubusercontent.com/21348463/194647157-0ae96990-cfca-4cca-b48e-379b0f8db2d3.gif)

I'm completely lost, been trying all afternoon 😕 
</div>

**Comment by SrPeterr** [comment]
This is what I see now...
This is my code:
```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Progress - Mazer Admin Dashboard</title>
    
    <link rel="stylesheet" href="assets/css/main/app.css">
    <link rel="stylesheet" href="assets/css/main/app-dark.css">
    <link rel="shortcut icon" href="assets/images/logo/favicon.svg" type="image/x-icon">
    <link rel="shortcut icon" href="assets/images/logo/favicon.png" type="image/png">
    @toastScripts
    <script src="{{ mix('js/app.js') }}" defer></script>
    @livewireStyles
    @livewireScripts
        
    
</head>

<body>
    <div>
    <livewire:toasts />
    </div>
```

I had to had a div on livewiretoast because I had a warning on the console, If I remove the div It will still look the same.

![Opera Snapshot_2022-10-10_120925_area51 edorasrp es](https://user-images.githubusercontent.com/21348463/194844099-80933a50-bfae-4208-956e-28158c40ae0e.png)

**Comment by SrPeterr** [comment]
I just find this error on the console:
```
dispatch.js:6 Uncaught RangeError: Maximum call stack size exceeded.
    at dispatch (dispatch.js:6:14)
    at Livewire.value (index.js:92:9)
    at bugs:84:29
    at dispatch (app.js:682:6)
    at Object.start (app.js:743:3)
    at notify.js:1:26634
    at bugs:76:13
    at dispatch (dispatch.js:6:14)
    at Livewire.value (index.js:92:9)
    at bugs:84:29
```

**Comment by widhyarsana** [comment]
I have the same issue

**Comment by RichardStyles** [comment]
Just for future references a `php artisan livewire:discover` (livewire v2) resolved this for me
