### ISSUE TITLE
unable to find livewire component toast

### ISSUE THREAD

**Issue by ashek1412** [usernotnull/tall-toasts#292]
Hi,
I successfully installed the package and it runs on the local machine.
but it fails when I run on server using Cpanel

please assist
![image](https://user-images.githubusercontent.com/18645594/197942843-411a3452-a212-45a3-9a9f-1ed90f32a871.png)

**Comment by usernotnull** [comment]
Running on CPanel is not a variable in any way, it can't be the problem. If livewire is running well, tall-toasts should also run without issue as it uses the same logic to inject the js component.

Your issue is somewhere else. I hope the troubleshooting section will help you resolve it.
