### ISSUE TITLE
Laravel 10 support

### ISSUE THREAD

**Issue by vodnicearv** [usernotnull/tall-toasts#359]
it would be nice to have support for Laravel 10

**Comment by usernotnull** [comment]
Will work on it when I'm off this weekend.

**Comment by usernotnull** [comment]
Update released before the weekend :)

**Comment by timgavin** [comment]
@usernotnull  I didn't want to open a new issue for this but I just wanted to say thanks for this awesome package; really appreciate it!

**Comment by usernotnull** [comment]
> @usernotnull  I didn't want to open a new issue for this but I just wanted to say thanks for this awesome package; really appreciate it!

@timgavin Thanks for your kind words 😊
