### ISSUE TITLE
Livewire v3 support

### ISSUE THREAD

**Issue by usernotnull** [usernotnull/tall-toasts#418]
I have received requests for upgrading to Livewire V3.

This tall-toast library will be upgraded after summer and after the livewire release is out of beta and stable.
In the meantime, if anyone wishes to speed up the process, I'm open to PRs.

Happy coding! 👋🏼

**Comment by r2luna** [comment]
#431 PR open :)

**Comment by usernotnull** [comment]
V2 released 🥳
https://github.com/usernotnull/tall-toasts/releases/tag/v2.0.0
