### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by RikoDEV** [usernotnull/tall-toasts#98]
### Description

Currently tall-toasts does not support the latest version of Laravel 9 due to an illuminate/contracts version conflict.

### To Reproduce

1. Install Laravel 9
2. Install tall-toasts

### Additional context

```
usernotnull/tall-toasts v1.3.0 requires illuminate/contracts ^v8.61 -> satisfiable by illuminate/contracts[v8.61.0, ..., 8.x-dev].
```

**Comment by usernotnull** [comment]
Thanks for raising this.
I'll be updating the library and testing soon to support Laravel 9.
